name: build custom codecs

on:
  workflow_dispatch:
    inputs:
      store_artifact:
        description: 'Store Artifacts'
        type: boolean
        default: false
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source tree
        uses: actions/checkout@v4
      - name: install build tools
        run: sudo apt update && sudo apt install -y nasm meson ninja-build
      - name: setting up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
      - name: clean output directories
        run: ./build.sh clean
        shell: bash
      - name: build arm64 codec
        id: build_arm64
        if: success()
        run: ./build.sh arm64
        shell: bash
      - name: build neon codec
        id: build_neon
        if: success()
        run: ./build.sh neon
        shell: bash
      - name: build x86_64 codec
        id: build_x86_64
        if: success()
        run: ./build.sh x86_64
        shell: bash
      - name: build x86 codec
        id: build_x86
        if: success()
        run: ./build.sh x86
        shell: bash
      - name: release artifacts
        id: release_artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && ${{ steps.build_arm64.outcome == 'success' }} && ${{ steps.build_neon.outcome == 'success' }} && ${{ steps.build_x86_64 == 'success' }} && ${{ steps.build_x86.outcome == 'success' }}
        with:
          files: output/*.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: save artifacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.release_artifacts.outcome != 'success' }} || ${{ inputs.store_artifact }}
        with:
          name: build-artifacts
          path: output/*.zip
